Repository antvis/F6, pull requests merged in 2021-08, with the labels that each got.

#35 feat: 增加plugin package
  packages/plugin/.eslintignore
  packages/plugin/.eslintrc.js
  packages/plugin/.fatherrc.js
  packages/plugin/.npmignore
  packages/plugin/.prettierignore
  packages/plugin/.prettierrc.js
  packages/plugin/README-zh_CN.md
  packages/plugin/README.md
  packages/plugin/global.d.ts
  packages/plugin/jest.config.js
  packages/plugin/package.json
  packages/plugin/src/index.ts
  packages/plugin/src/timebar/index.ts
  packages/plugin/tsconfig.json
  packages/plugin/webpack.config.js
  packages/plugin/webpack.dev.config.js
Labels: PR: unreviewed

#34 feat: 增加dom支持
  packages/f6-alipay/demo/app.json
  packages/f6-alipay/demo/mini.project.json
  packages/f6-alipay/demo/package.json
  packages/f6-alipay/demo/pages/g6/g6.js
  packages/f6-alipay/demo/pages/g6/g6.json
  packages/f6-alipay/demo/pages/image/image.js
  packages/f6-alipay/demo/pages/image/image.json
  packages/f6-alipay/demo/pages/native-canvas/index.json
  packages/f6-alipay/demo/pages/native-test-fullpage/index.js
  packages/f6-alipay/demo/pages/native-test-fullpage/index.json
  packages/f6-alipay/demo/pages/native-test/native-test.js
  packages/f6-alipay/demo/pages/native-test/native-test.json
  packages/f6-ui/.eslintignore
  packages/f6-ui/.eslintrc.js
  packages/f6-ui/.fatherrc.js
  packages/f6-ui/.npmignore
  packages/f6-ui/.prettierignore
  packages/f6-ui/.prettierrc.js
  packages/f6-ui/README-zh_CN.md
  packages/f6-ui/README.md
  packages/f6-ui/global.d.ts
  packages/f6-ui/jest.config.js
  packages/f6-ui/package.json
  packages/f6-ui/src/index.ts
  packages/f6-ui/src/om/css.ts
  packages/f6-ui/src/om/dom.ts
  packages/f6-ui/src/om/style.ts
  packages/f6-ui/src/parser/attrParser.ts
  packages/f6-ui/src/uiNode/UIDivNode.ts
  packages/f6-ui/src/uiNode/UIImageNode.ts
  packages/f6-ui/src/uiNode/UIRootNode.ts
  packages/f6-ui/src/uiNode/UIShapeNode.ts
  packages/f6-ui/src/uiNode/UITextNode.ts
  packages/f6-ui/src/uiNode/UITree.ts
  packages/f6-ui/src/uiNode/base.ts
  packages/f6-ui/src/uiNode/factory.ts
  packages/f6-ui/src/uiNode/index.ts
  packages/f6-ui/src/utils/index.ts
  packages/f6-ui/src/utils/parser.ts
  packages/f6-ui/src/utils/ui.ts
  packages/f6-ui/tsconfig.json
  packages/f6-ui/webpack.config.js
  packages/f6-ui/webpack.dev.config.js
  packages/f6/src/global.ts
  packages/f6/src/graph/graph.ts
  packages/f6/stories/index.stories.tsx
  packages/f6/stories/uiTest/data.ts
  packages/f6/stories/uiTest/index.tsx
Labels: new feature, PR: unreviewed

#39 add snapLine plugin
  packages/f6/src/index.ts
  packages/f6/stories/index.stories.tsx
  packages/f6/stories/snapLine/data.ts
  packages/f6/stories/snapLine/index.tsx
  packages/plugin/package.json
  packages/plugin/src/base.ts
  packages/plugin/src/index.ts
  packages/plugin/src/snapLine/index.ts
Labels: PR: reviewed-approved

#38 feat: 增加f6-ui重排、生命周期
  packages/f6-ui/src/index.ts
  packages/f6-ui/src/uiNode/UIDivNode.ts
  packages/f6-ui/src/uiNode/UIImageNode.ts
  packages/f6-ui/src/uiNode/UIShapeNode.ts
  packages/f6-ui/src/uiNode/UITextNode.ts
  packages/f6-ui/src/uiNode/UITree.ts
  packages/f6-ui/src/uiNode/base.ts
Labels: PR: reviewed-approved, PR: reviewed-changes-requested

#40 fix: clearTimeout时同时清除引用，防止外部误清除
  packages/hammer/src/recognizers/press.js
  packages/hammer/src/recognizers/tap.js
Labels: bug👾, PR: unreviewed

#37 feat: 增加timebar
  packages/f6/package.json
  packages/f6/stories/uiTest/index.tsx
  packages/plugin/package.json
  packages/plugin/src/base.ts
  packages/plugin/src/index.ts
  packages/plugin/src/timebar/dispatcher.ts
  packages/plugin/src/timebar/index.ts
  packages/plugin/src/timebar/type/controlBar.ts
  packages/plugin/src/timebar/type/slider.ts
  packages/plugin/src/timebar/type/tick.ts
  packages/plugin/src/timebar/type/timeBar.ts
  packages/plugin/src/timebar/ui/controlBar/controlBtn.ts
  packages/plugin/src/timebar/ui/controlBar/index.ts
  packages/plugin/src/timebar/ui/controlBar/playBtn.ts
  packages/plugin/src/timebar/ui/index.ts
  packages/plugin/src/timebar/ui/progressBar/index.ts
  packages/plugin/src/timebar/ui/progressBar/tick.ts
  packages/plugin/src/timebar/ui/progressBar/trend.ts
  packages/plugin/src/timebar/ui/slider/simpleSlider.ts
  packages/plugin/src/timebar/ui/slider/slideTicker.ts
  packages/plugin/src/timebar/ui/slider/sliderLogic.ts
  packages/plugin/src/timebar/ui/slider/trendSlider.ts
  packages/plugin/src/timebar/utils/const.ts
  packages/plugin/src/timebar/utils/path.ts
  packages/plugin/src/timebar/utils/player.ts
Labels: new feature, PR: unreviewed

#44 新增缩放滑块插件
  package.json
  packages/f6/stories/index.stories.tsx
  packages/f6/stories/pluginZoomSlider/data.ts
  packages/f6/stories/pluginZoomSlider/index.tsx
  packages/plugin/src/index.ts
  packages/plugin/src/zoomSlider/index.ts
Labels: PR: unreviewed
